"""new_velocity_entries

Revision ID: 0ba351dd5171
Revises: 9421cae2a38a
Create Date: 2021-02-01 17:30:51.101331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ba351dd5171'
down_revision = '9421cae2a38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_velocity',
    sa.Column('sprint_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('commitment', sa.FLOAT(), nullable=False),
    sa.Column('completed', sa.FLOAT(), nullable=False),
    sa.Column('start_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('end_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['jira_projects.id'], ),
    sa.PrimaryKeyConstraint('sprint_id'),
    sa.UniqueConstraint('sprint_id')
    )
    op.create_foreign_key(None, 'jira_work_stat', 'jira_velocity', ['sprint_id'], ['sprint_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jira_work_stat', type_='foreignkey')
    op.drop_table('jira_velocity')
    # ### end Alembic commands ###
