"""velocity_stats

Revision ID: 620ab81c8f8f
Revises: 50c669c31ca0
Create Date: 2021-01-15 15:34:43.398641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620ab81c8f8f'
down_revision = '50c669c31ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jira-velocity', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jira-velocity', 'created_at')
    # ### end Alembic commands ###
