"""worklog

Revision ID: 7e916f5e5785
Revises: e2db8954bc5d
Create Date: 2021-02-02 23:53:49.740159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e916f5e5785'
down_revision = 'e2db8954bc5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jira_work_stat', sa.Column('worklog', sa.INTEGER(), nullable=True))
    op.drop_column('jira_work_stat', 'completed_worklog')
    op.drop_column('jira_work_stat', 'total_worklog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jira_work_stat', sa.Column('total_worklog', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('jira_work_stat', sa.Column('completed_worklog', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('jira_work_stat', 'worklog')
    # ### end Alembic commands ###
