"""new_velocity_entries

Revision ID: 9421cae2a38a
Revises: af76bba52a58
Create Date: 2021-02-01 14:33:17.968525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9421cae2a38a'
down_revision = 'af76bba52a58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jira_velocity', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'jira_velocity', ['sprint_id'])
    op.drop_constraint('jira_velocity_project_key_fkey', 'jira_velocity', type_='foreignkey')
    op.create_foreign_key(None, 'jira_velocity', 'jira_projects', ['project_id'], ['id'])
    op.drop_column('jira_velocity', 'project_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jira_velocity', sa.Column('project_key', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'jira_velocity', type_='foreignkey')
    op.create_foreign_key('jira_velocity_project_key_fkey', 'jira_velocity', 'jira_projects', ['project_key'], ['id'])
    op.drop_constraint(None, 'jira_velocity', type_='unique')
    op.drop_column('jira_velocity', 'project_id')
    # ### end Alembic commands ###
