"""jira_velocity

Revision ID: af76bba52a58
Revises: bacfc24b656d
Create Date: 2021-01-29 13:31:36.301731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af76bba52a58'
down_revision = 'bacfc24b656d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_key', sa.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_key')
    )
    op.create_table('jira_velocity',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('project_key', sa.Integer(), nullable=False),
    sa.Column('sprint_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('commitment', sa.FLOAT(), nullable=False),
    sa.Column('completed', sa.FLOAT(), nullable=False),
    sa.Column('start_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('end_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_key'], ['jira_projects.id'], ),
    sa.PrimaryKeyConstraint('sprint_id'),
    sa.UniqueConstraint('sprint_id')
    )
    op.create_table('jira_work_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=False),
    sa.Column('worklog', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['jira_projects.id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['jira_velocity.sprint_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jira_work_stat')
    op.drop_table('jira_velocity')
    op.drop_table('jira_projects')
    # ### end Alembic commands ###
