"""add_dev_count_column

Revision ID: b9fed7948d1e
Revises: 27d7bc410b70
Create Date: 2021-02-10 17:40:39.210053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9fed7948d1e'
down_revision = '27d7bc410b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jira_work_stat', sa.Column('dev_count', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jira_work_stat', 'dev_count')
    # ### end Alembic commands ###
