"""velocity_stats

Revision ID: bacfc24b656d
Revises: 620ab81c8f8f
Create Date: 2021-01-19 13:41:27.276987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bacfc24b656d'
down_revision = '620ab81c8f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_velocity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_key', sa.VARCHAR(length=256), nullable=False),
    sa.Column('sprint_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('commitment', sa.FLOAT(), nullable=False),
    sa.Column('completed', sa.FLOAT(), nullable=False),
    sa.Column('start_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('end_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sprint_id')
    )
    op.drop_table('jira-velocity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira-velocity',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"jira-velocity_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('project_key', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('sprint_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('commitment', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('completed', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('start_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='jira-velocity_pkey'),
    sa.UniqueConstraint('name', name='jira-velocity_name_key'),
    sa.UniqueConstraint('sprint_id', name='jira-velocity_sprint_id_key')
    )
    op.drop_table('jira_velocity')
    # ### end Alembic commands ###
