"""worklog

Revision ID: e2db8954bc5d
Revises: 0ba351dd5171
Create Date: 2021-02-02 23:31:17.597182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2db8954bc5d'
down_revision = '0ba351dd5171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_work_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=False),
    sa.Column('completed_worklog', sa.INTEGER(), nullable=True),
    sa.Column('total_worklog', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['jira_projects.id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['jira_velocity.sprint_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'jira_velocity', ['sprint_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jira_velocity', type_='unique')
    op.drop_table('jira_work_stat')
    # ### end Alembic commands ###
