"""new_worklog

Revision ID: f26fd897137f
Revises: 7e916f5e5785
Create Date: 2021-02-08 14:53:18.804134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f26fd897137f'
down_revision = '7e916f5e5785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jira_work_stat', sa.Column('completed_worklog', sa.INTEGER(), nullable=True))
    op.add_column('jira_work_stat', sa.Column('total_worklog', sa.INTEGER(), nullable=True))
    op.alter_column('jira_work_stat', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('jira_work_stat', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jira_work_stat', 'sprint_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('jira_work_stat', 'worklog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jira_work_stat', sa.Column('worklog', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('jira_work_stat', 'sprint_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jira_work_stat', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jira_work_stat', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('jira_work_stat', 'total_worklog')
    op.drop_column('jira_work_stat', 'completed_worklog')
    # ### end Alembic commands ###
